export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const FETCH_DISHES = 'POST/FETCH_DISHES'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'

export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'